set -g mouse on

setw -g mode-keys vi

set -g status-position bottom

set-option -g history-limit 5000

set-option -g default-shell /usr/bin/zsh
# reload tmux
unbind r
bind r source-file ~/.tmux.conf

# remap prefix 
unbind C-b
unbind M-Space
set-option -g prefix M-Space
bind-key M-Space send-prefix

# Better splitting
bind -n M-\\ split-window -h
bind -n M-- split-window -v
unbind '"' 
unbind %


# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# Jumping through windows and making new ones w/o prefix
bind-key -n M-Tab next-window
bind-key Tab previous-window
bind Space last-window  # Toggle Recent window
bind n new-window -c "#{pane_current_path}"

# List of plugins
set -g @tpm_plugins '           \
   tmux-plugins/tpm             \
   tmux-plugins/tmux-plugins/tpm \
   tmux-plugins/dracula/tmux     \
'

# Theme options
set -g @dracula-plugins "cpu-usage ram-usage git ssh-session"
set -g @dracula-show-empty-plugins false
set -g @dracula-show-location false
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session

# Init Tmux plugin manager (keep this line at very bottom)
run '~/.tmux/plugins/tpm/tpm'
