[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = \
rightalt = layer(weomods)

[weomods:C]

h = left
j = down
k = up
l = right

q = @
w = =
e = -
r = '

a = (
s = )
d = [
f = ]
g = #

c = ^
v = `
[weomods+shift]

q = &

a = !
s = ?
g = %

c = *
